/* XboxWebApi.h generated by valac 0.40.15, the Vala compiler, do not modify */


#ifndef __XBOXWEBAPI_H__
#define __XBOXWEBAPI_H__

#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <gee.h>

G_BEGIN_DECLS


#define XBOX_WEB_API_TYPE_AUTH (xbox_web_api_auth_get_type ())
#define XBOX_WEB_API_AUTH(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_TYPE_AUTH, XboxWebApiAuth))
#define XBOX_WEB_API_AUTH_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_TYPE_AUTH, XboxWebApiAuthClass))
#define XBOX_WEB_API_IS_AUTH(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_TYPE_AUTH))
#define XBOX_WEB_API_IS_AUTH_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_TYPE_AUTH))
#define XBOX_WEB_API_AUTH_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_TYPE_AUTH, XboxWebApiAuthClass))

typedef struct _XboxWebApiAuth XboxWebApiAuth;
typedef struct _XboxWebApiAuthClass XboxWebApiAuthClass;
typedef struct _XboxWebApiAuthPrivate XboxWebApiAuthPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY (xbox_web_api_authentication_model_windows_live_authentication_query_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_AUTHENTICATION_QUERY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY, XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_AUTHENTICATION_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY, XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_AUTHENTICATION_QUERY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_AUTHENTICATION_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_AUTHENTICATION_QUERY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_AUTHENTICATION_QUERY, XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryClass))

typedef struct _XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryClass XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryClass;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryPrivate XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY (xbox_web_api_authentication_model_windows_live_refresh_query_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_REFRESH_QUERY(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY, XboxWebApiAuthenticationModelWindowsLiveRefreshQuery))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_REFRESH_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY, XboxWebApiAuthenticationModelWindowsLiveRefreshQueryClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_REFRESH_QUERY(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_REFRESH_QUERY_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_REFRESH_QUERY_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_REFRESH_QUERY, XboxWebApiAuthenticationModelWindowsLiveRefreshQueryClass))

typedef struct _XboxWebApiAuthenticationModelWindowsLiveRefreshQuery XboxWebApiAuthenticationModelWindowsLiveRefreshQuery;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveRefreshQueryClass XboxWebApiAuthenticationModelWindowsLiveRefreshQueryClass;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveRefreshQueryPrivate XboxWebApiAuthenticationModelWindowsLiveRefreshQueryPrivate;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN (xbox_web_api_authentication_base_auth_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_BASE_AUTH_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN, XboxWebApiAuthenticationBaseAuthToken))
#define XBOX_WEB_API_AUTHENTICATION_BASE_AUTH_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN, XboxWebApiAuthenticationBaseAuthTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_BASE_AUTH_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_BASE_AUTH_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_BASE_AUTH_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_BASE_AUTH_TOKEN, XboxWebApiAuthenticationBaseAuthTokenClass))

typedef struct _XboxWebApiAuthenticationBaseAuthToken XboxWebApiAuthenticationBaseAuthToken;
typedef struct _XboxWebApiAuthenticationBaseAuthTokenClass XboxWebApiAuthenticationBaseAuthTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN (xbox_web_api_authentication_refresh_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_REFRESH_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN, XboxWebApiAuthenticationRefreshToken))
#define XBOX_WEB_API_AUTHENTICATION_REFRESH_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN, XboxWebApiAuthenticationRefreshTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_REFRESH_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_REFRESH_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_REFRESH_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_REFRESH_TOKEN, XboxWebApiAuthenticationRefreshTokenClass))

typedef struct _XboxWebApiAuthenticationRefreshToken XboxWebApiAuthenticationRefreshToken;
typedef struct _XboxWebApiAuthenticationRefreshTokenClass XboxWebApiAuthenticationRefreshTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE (xbox_web_api_authentication_model_windows_live_response_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE, XboxWebApiAuthenticationModelWindowsLiveResponse))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE, XboxWebApiAuthenticationModelWindowsLiveResponseClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_WINDOWS_LIVE_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_WINDOWS_LIVE_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_WINDOWS_LIVE_RESPONSE, XboxWebApiAuthenticationModelWindowsLiveResponseClass))

typedef struct _XboxWebApiAuthenticationModelWindowsLiveResponse XboxWebApiAuthenticationModelWindowsLiveResponse;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveResponseClass XboxWebApiAuthenticationModelWindowsLiveResponseClass;
typedef struct _XboxWebApiAuthenticationModelWindowsLiveResponsePrivate XboxWebApiAuthenticationModelWindowsLiveResponsePrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST (xbox_web_api_authentication_model_xasd_request_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST, XboxWebApiAuthenticationModelXASDRequest))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST, XboxWebApiAuthenticationModelXASDRequestClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASD_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASD_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_REQUEST, XboxWebApiAuthenticationModelXASDRequestClass))

typedef struct _XboxWebApiAuthenticationModelXASDRequest XboxWebApiAuthenticationModelXASDRequest;
typedef struct _XboxWebApiAuthenticationModelXASDRequestClass XboxWebApiAuthenticationModelXASDRequestClass;
typedef struct _XboxWebApiAuthenticationModelXASDRequestPrivate XboxWebApiAuthenticationModelXASDRequestPrivate;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN (xbox_web_api_authentication_access_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_ACCESS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN, XboxWebApiAuthenticationAccessToken))
#define XBOX_WEB_API_AUTHENTICATION_ACCESS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN, XboxWebApiAuthenticationAccessTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_ACCESS_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_ACCESS_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_ACCESS_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_ACCESS_TOKEN, XboxWebApiAuthenticationAccessTokenClass))

typedef struct _XboxWebApiAuthenticationAccessToken XboxWebApiAuthenticationAccessToken;
typedef struct _XboxWebApiAuthenticationAccessTokenClass XboxWebApiAuthenticationAccessTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES (xbox_web_api_authentication_model_xasd_properties_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES, XboxWebApiAuthenticationModelXASDProperties))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES, XboxWebApiAuthenticationModelXASDPropertiesClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASD_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASD_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASD_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASD_PROPERTIES, XboxWebApiAuthenticationModelXASDPropertiesClass))

typedef struct _XboxWebApiAuthenticationModelXASDProperties XboxWebApiAuthenticationModelXASDProperties;
typedef struct _XboxWebApiAuthenticationModelXASDPropertiesClass XboxWebApiAuthenticationModelXASDPropertiesClass;
typedef struct _XboxWebApiAuthenticationModelXASDPropertiesPrivate XboxWebApiAuthenticationModelXASDPropertiesPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE (xbox_web_api_authentication_model_xas_response_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAS_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE, XboxWebApiAuthenticationModelXASResponse))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAS_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE, XboxWebApiAuthenticationModelXASResponseClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAS_RESPONSE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAS_RESPONSE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAS_RESPONSE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAS_RESPONSE, XboxWebApiAuthenticationModelXASResponseClass))

typedef struct _XboxWebApiAuthenticationModelXASResponse XboxWebApiAuthenticationModelXASResponse;
typedef struct _XboxWebApiAuthenticationModelXASResponseClass XboxWebApiAuthenticationModelXASResponseClass;
typedef struct _XboxWebApiAuthenticationModelXASResponsePrivate XboxWebApiAuthenticationModelXASResponsePrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION (xbox_web_api_authentication_model_xbox_user_information_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XBOX_USER_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION, XboxWebApiAuthenticationModelXboxUserInformation))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XBOX_USER_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION, XboxWebApiAuthenticationModelXboxUserInformationClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XBOX_USER_INFORMATION(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XBOX_USER_INFORMATION_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XBOX_USER_INFORMATION_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XBOX_USER_INFORMATION, XboxWebApiAuthenticationModelXboxUserInformationClass))

typedef struct _XboxWebApiAuthenticationModelXboxUserInformation XboxWebApiAuthenticationModelXboxUserInformation;
typedef struct _XboxWebApiAuthenticationModelXboxUserInformationClass XboxWebApiAuthenticationModelXboxUserInformationClass;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST (xbox_web_api_authentication_model_xast_request_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST, XboxWebApiAuthenticationModelXASTRequest))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST, XboxWebApiAuthenticationModelXASTRequestClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAST_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAST_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_REQUEST, XboxWebApiAuthenticationModelXASTRequestClass))

typedef struct _XboxWebApiAuthenticationModelXASTRequest XboxWebApiAuthenticationModelXASTRequest;
typedef struct _XboxWebApiAuthenticationModelXASTRequestClass XboxWebApiAuthenticationModelXASTRequestClass;
typedef struct _XboxWebApiAuthenticationModelXASTRequestPrivate XboxWebApiAuthenticationModelXASTRequestPrivate;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN (xbox_web_api_authentication_device_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_DEVICE_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN, XboxWebApiAuthenticationDeviceToken))
#define XBOX_WEB_API_AUTHENTICATION_DEVICE_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN, XboxWebApiAuthenticationDeviceTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_DEVICE_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_DEVICE_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_DEVICE_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_DEVICE_TOKEN, XboxWebApiAuthenticationDeviceTokenClass))

typedef struct _XboxWebApiAuthenticationDeviceToken XboxWebApiAuthenticationDeviceToken;
typedef struct _XboxWebApiAuthenticationDeviceTokenClass XboxWebApiAuthenticationDeviceTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES (xbox_web_api_authentication_model_xast_properties_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES, XboxWebApiAuthenticationModelXASTProperties))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES, XboxWebApiAuthenticationModelXASTPropertiesClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAST_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XAST_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XAST_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XAST_PROPERTIES, XboxWebApiAuthenticationModelXASTPropertiesClass))

typedef struct _XboxWebApiAuthenticationModelXASTProperties XboxWebApiAuthenticationModelXASTProperties;
typedef struct _XboxWebApiAuthenticationModelXASTPropertiesClass XboxWebApiAuthenticationModelXASTPropertiesClass;
typedef struct _XboxWebApiAuthenticationModelXASTPropertiesPrivate XboxWebApiAuthenticationModelXASTPropertiesPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST (xbox_web_api_authentication_model_xasu_request_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST, XboxWebApiAuthenticationModelXASURequest))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST, XboxWebApiAuthenticationModelXASURequestClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASU_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASU_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_REQUEST, XboxWebApiAuthenticationModelXASURequestClass))

typedef struct _XboxWebApiAuthenticationModelXASURequest XboxWebApiAuthenticationModelXASURequest;
typedef struct _XboxWebApiAuthenticationModelXASURequestClass XboxWebApiAuthenticationModelXASURequestClass;
typedef struct _XboxWebApiAuthenticationModelXASURequestPrivate XboxWebApiAuthenticationModelXASURequestPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES (xbox_web_api_authentication_model_xasu_properties_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES, XboxWebApiAuthenticationModelXASUProperties))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES, XboxWebApiAuthenticationModelXASUPropertiesClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASU_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XASU_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XASU_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XASU_PROPERTIES, XboxWebApiAuthenticationModelXASUPropertiesClass))

typedef struct _XboxWebApiAuthenticationModelXASUProperties XboxWebApiAuthenticationModelXASUProperties;
typedef struct _XboxWebApiAuthenticationModelXASUPropertiesClass XboxWebApiAuthenticationModelXASUPropertiesClass;
typedef struct _XboxWebApiAuthenticationModelXASUPropertiesPrivate XboxWebApiAuthenticationModelXASUPropertiesPrivate;
typedef struct _XboxWebApiAuthenticationModelXboxUserInformationPrivate XboxWebApiAuthenticationModelXboxUserInformationPrivate;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST (xbox_web_api_authentication_model_xsts_request_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST, XboxWebApiAuthenticationModelXSTSRequest))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST, XboxWebApiAuthenticationModelXSTSRequestClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XSTS_REQUEST(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XSTS_REQUEST_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_REQUEST_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_REQUEST, XboxWebApiAuthenticationModelXSTSRequestClass))

typedef struct _XboxWebApiAuthenticationModelXSTSRequest XboxWebApiAuthenticationModelXSTSRequest;
typedef struct _XboxWebApiAuthenticationModelXSTSRequestClass XboxWebApiAuthenticationModelXSTSRequestClass;
typedef struct _XboxWebApiAuthenticationModelXSTSRequestPrivate XboxWebApiAuthenticationModelXSTSRequestPrivate;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN (xbox_web_api_authentication_user_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_USER_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN, XboxWebApiAuthenticationUserToken))
#define XBOX_WEB_API_AUTHENTICATION_USER_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN, XboxWebApiAuthenticationUserTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_USER_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_USER_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_USER_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_USER_TOKEN, XboxWebApiAuthenticationUserTokenClass))

typedef struct _XboxWebApiAuthenticationUserToken XboxWebApiAuthenticationUserToken;
typedef struct _XboxWebApiAuthenticationUserTokenClass XboxWebApiAuthenticationUserTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN (xbox_web_api_authentication_title_token_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_TITLE_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN, XboxWebApiAuthenticationTitleToken))
#define XBOX_WEB_API_AUTHENTICATION_TITLE_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN, XboxWebApiAuthenticationTitleTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_TITLE_TOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_TITLE_TOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN))
#define XBOX_WEB_API_AUTHENTICATION_TITLE_TOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_TITLE_TOKEN, XboxWebApiAuthenticationTitleTokenClass))

typedef struct _XboxWebApiAuthenticationTitleToken XboxWebApiAuthenticationTitleToken;
typedef struct _XboxWebApiAuthenticationTitleTokenClass XboxWebApiAuthenticationTitleTokenClass;

#define XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES (xbox_web_api_authentication_model_xsts_properties_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES, XboxWebApiAuthenticationModelXSTSProperties))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES, XboxWebApiAuthenticationModelXSTSPropertiesClass))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XSTS_PROPERTIES(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_IS_XSTS_PROPERTIES_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES))
#define XBOX_WEB_API_AUTHENTICATION_MODEL_XSTS_PROPERTIES_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_MODEL_TYPE_XSTS_PROPERTIES, XboxWebApiAuthenticationModelXSTSPropertiesClass))

typedef struct _XboxWebApiAuthenticationModelXSTSProperties XboxWebApiAuthenticationModelXSTSProperties;
typedef struct _XboxWebApiAuthenticationModelXSTSPropertiesClass XboxWebApiAuthenticationModelXSTSPropertiesClass;
typedef struct _XboxWebApiAuthenticationModelXSTSPropertiesPrivate XboxWebApiAuthenticationModelXSTSPropertiesPrivate;
typedef struct _XboxWebApiAuthenticationBaseAuthTokenPrivate XboxWebApiAuthenticationBaseAuthTokenPrivate;
typedef struct _XboxWebApiAuthenticationAccessTokenPrivate XboxWebApiAuthenticationAccessTokenPrivate;
typedef struct _XboxWebApiAuthenticationDeviceTokenPrivate XboxWebApiAuthenticationDeviceTokenPrivate;
typedef struct _XboxWebApiAuthenticationRefreshTokenPrivate XboxWebApiAuthenticationRefreshTokenPrivate;
typedef struct _XboxWebApiAuthenticationTitleTokenPrivate XboxWebApiAuthenticationTitleTokenPrivate;
typedef struct _XboxWebApiAuthenticationUserTokenPrivate XboxWebApiAuthenticationUserTokenPrivate;

#define XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN (xbox_web_api_authentication_xtoken_get_type ())
#define XBOX_WEB_API_AUTHENTICATION_XTOKEN(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN, XboxWebApiAuthenticationXToken))
#define XBOX_WEB_API_AUTHENTICATION_XTOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN, XboxWebApiAuthenticationXTokenClass))
#define XBOX_WEB_API_AUTHENTICATION_IS_XTOKEN(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN))
#define XBOX_WEB_API_AUTHENTICATION_IS_XTOKEN_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN))
#define XBOX_WEB_API_AUTHENTICATION_XTOKEN_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), XBOX_WEB_API_AUTHENTICATION_TYPE_XTOKEN, XboxWebApiAuthenticationXTokenClass))

typedef struct _XboxWebApiAuthenticationXToken XboxWebApiAuthenticationXToken;
typedef struct _XboxWebApiAuthenticationXTokenClass XboxWebApiAuthenticationXTokenClass;
typedef struct _XboxWebApiAuthenticationXTokenPrivate XboxWebApiAuthenticationXTokenPrivate;

struct _XboxWebApiAuth {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthPrivate * priv;
};

struct _XboxWebApiAuthClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuth *self);
};

struct _XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryPrivate * priv;
};

struct _XboxWebApiAuthenticationModelWindowsLiveAuthenticationQueryClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery *self);
};

struct _XboxWebApiAuthenticationModelWindowsLiveRefreshQuery {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelWindowsLiveRefreshQueryPrivate * priv;
};

struct _XboxWebApiAuthenticationModelWindowsLiveRefreshQueryClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery *self);
};

struct _XboxWebApiAuthenticationModelWindowsLiveResponse {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelWindowsLiveResponsePrivate * priv;
	gchar* access_token;
	gint expires_in;
	gchar* refresh_token;
	gchar* user_id;
	gchar* scope;
	gchar* token_type;
};

struct _XboxWebApiAuthenticationModelWindowsLiveResponseClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelWindowsLiveResponse *self);
};

struct _XboxWebApiAuthenticationModelXASDRequest {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASDRequestPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASDRequestClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASDRequest *self);
};

struct _XboxWebApiAuthenticationModelXASDProperties {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASDPropertiesPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASDPropertiesClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASDProperties *self);
};

struct _XboxWebApiAuthenticationModelXASResponse {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASResponsePrivate * priv;
	gchar* token;
	GDateTime* issue_instant;
	GDateTime* not_after;
	GeeHashMap* display_claims;
};

struct _XboxWebApiAuthenticationModelXASResponseClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASResponse *self);
};

struct _XboxWebApiAuthenticationModelXASTRequest {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASTRequestPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASTRequestClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASTRequest *self);
};

struct _XboxWebApiAuthenticationModelXASTProperties {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASTPropertiesPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASTPropertiesClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASTProperties *self);
};

struct _XboxWebApiAuthenticationModelXASURequest {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASURequestPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASURequestClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASURequest *self);
};

struct _XboxWebApiAuthenticationModelXASUProperties {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXASUPropertiesPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXASUPropertiesClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXASUProperties *self);
};

struct _XboxWebApiAuthenticationModelXboxUserInformation {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXboxUserInformationPrivate * priv;
	gchar* age_group;
	gchar* gamertag;
	gchar* privileges;
	gchar* user_settings_restrictions;
	gchar* user_title_restrictions;
	gulong xbox_user_id;
	gchar* user_hash;
};

struct _XboxWebApiAuthenticationModelXboxUserInformationClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXboxUserInformation *self);
};

struct _XboxWebApiAuthenticationModelXSTSRequest {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXSTSRequestPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXSTSRequestClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXSTSRequest *self);
};

struct _XboxWebApiAuthenticationModelXSTSProperties {
	GTypeInstance parent_instance;
	volatile int ref_count;
	XboxWebApiAuthenticationModelXSTSPropertiesPrivate * priv;
};

struct _XboxWebApiAuthenticationModelXSTSPropertiesClass {
	GTypeClass parent_class;
	void (*finalize) (XboxWebApiAuthenticationModelXSTSProperties *self);
};

struct _XboxWebApiAuthenticationBaseAuthToken {
	GObject parent_instance;
	XboxWebApiAuthenticationBaseAuthTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationBaseAuthTokenClass {
	GObjectClass parent_class;
};

struct _XboxWebApiAuthenticationAccessToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationAccessTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationAccessTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};

struct _XboxWebApiAuthenticationDeviceToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationDeviceTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationDeviceTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};

struct _XboxWebApiAuthenticationRefreshToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationRefreshTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationRefreshTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};

struct _XboxWebApiAuthenticationTitleToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationTitleTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationTitleTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};

struct _XboxWebApiAuthenticationUserToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationUserTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationUserTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};

struct _XboxWebApiAuthenticationXToken {
	XboxWebApiAuthenticationBaseAuthToken parent_instance;
	XboxWebApiAuthenticationXTokenPrivate * priv;
};

struct _XboxWebApiAuthenticationXTokenClass {
	XboxWebApiAuthenticationBaseAuthTokenClass parent_class;
};


gpointer xbox_web_api_auth_ref (gpointer instance);
void xbox_web_api_auth_unref (gpointer instance);
GParamSpec* xbox_web_api_param_spec_auth (const gchar* name,
                                          const gchar* nick,
                                          const gchar* blurb,
                                          GType object_type,
                                          GParamFlags flags);
void xbox_web_api_value_set_auth (GValue* value,
                                  gpointer v_object);
void xbox_web_api_value_take_auth (GValue* value,
                                   gpointer v_object);
gpointer xbox_web_api_value_get_auth (const GValue* value);
GType xbox_web_api_auth_get_type (void) G_GNUC_CONST;
gint xbox_web_api_auth_login (XboxWebApiAuth* self);
gint xbox_web_api_auth_logout (XboxWebApiAuth* self);
XboxWebApiAuth* xbox_web_api_auth_new (void);
XboxWebApiAuth* xbox_web_api_auth_construct (GType object_type);
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_CLIENT_ID "0000000048093EE3"
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_SCOPE "service::user.auth.xboxlive.com::MBI_SSL"
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_AUTHORIZE_URL "https://login.live.com/oauth20_authorize.srf"
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_REFRESH_TOKEN_URL "https://login.live.com/oauth20_token.srf"
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_REDIRECT_URL "https://login.live.com/oauth20_desktop.srf"
#define XBOX_WEB_API_AUTHENTICATION_WINDOWS_LIVE_CONSTANTS_RESPONSE_TYPE "token"
gpointer xbox_web_api_authentication_model_windows_live_authentication_query_ref (gpointer instance);
void xbox_web_api_authentication_model_windows_live_authentication_query_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_windows_live_authentication_query (const gchar* name,
                                                                                            const gchar* nick,
                                                                                            const gchar* blurb,
                                                                                            GType object_type,
                                                                                            GParamFlags flags);
void xbox_web_api_authentication_model_value_set_windows_live_authentication_query (GValue* value,
                                                                                    gpointer v_object);
void xbox_web_api_authentication_model_value_take_windows_live_authentication_query (GValue* value,
                                                                                     gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_windows_live_authentication_query (const GValue* value);
GType xbox_web_api_authentication_model_windows_live_authentication_query_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* xbox_web_api_authentication_model_windows_live_authentication_query_new (const gchar* response_type,
                                                                                                                                      const gchar* scope,
                                                                                                                                      const gchar* redirect_uri,
                                                                                                                                      const gchar* client_id,
                                                                                                                                      const gchar* display,
                                                                                                                                      const gchar* locale);
XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* xbox_web_api_authentication_model_windows_live_authentication_query_construct (GType object_type,
                                                                                                                                            const gchar* response_type,
                                                                                                                                            const gchar* scope,
                                                                                                                                            const gchar* redirect_uri,
                                                                                                                                            const gchar* client_id,
                                                                                                                                            const gchar* display,
                                                                                                                                            const gchar* locale);
GHashTable* xbox_web_api_authentication_model_windows_live_authentication_query_get_query (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_response_type (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_scope (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_redirect_uri (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_client_id (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_display (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_authentication_query_get_locale (XboxWebApiAuthenticationModelWindowsLiveAuthenticationQuery* self);
gpointer xbox_web_api_authentication_model_windows_live_refresh_query_ref (gpointer instance);
void xbox_web_api_authentication_model_windows_live_refresh_query_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_windows_live_refresh_query (const gchar* name,
                                                                                     const gchar* nick,
                                                                                     const gchar* blurb,
                                                                                     GType object_type,
                                                                                     GParamFlags flags);
void xbox_web_api_authentication_model_value_set_windows_live_refresh_query (GValue* value,
                                                                             gpointer v_object);
void xbox_web_api_authentication_model_value_take_windows_live_refresh_query (GValue* value,
                                                                              gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_windows_live_refresh_query (const GValue* value);
GType xbox_web_api_authentication_model_windows_live_refresh_query_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_base_auth_token_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_refresh_token_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* xbox_web_api_authentication_model_windows_live_refresh_query_new (XboxWebApiAuthenticationRefreshToken* refresh_token,
                                                                                                                        const gchar* grant_type,
                                                                                                                        const gchar* client_id,
                                                                                                                        const gchar* scope);
XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* xbox_web_api_authentication_model_windows_live_refresh_query_construct (GType object_type,
                                                                                                                              XboxWebApiAuthenticationRefreshToken* refresh_token,
                                                                                                                              const gchar* grant_type,
                                                                                                                              const gchar* client_id,
                                                                                                                              const gchar* scope);
GeeHashMap* xbox_web_api_authentication_model_windows_live_refresh_query_get_query (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_refresh_query_get_grant_type (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_refresh_query_get_client_id (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_refresh_query_get_scope (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* self);
const gchar* xbox_web_api_authentication_model_windows_live_refresh_query_get_refresh_token (XboxWebApiAuthenticationModelWindowsLiveRefreshQuery* self);
gpointer xbox_web_api_authentication_model_windows_live_response_ref (gpointer instance);
void xbox_web_api_authentication_model_windows_live_response_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_windows_live_response (const gchar* name,
                                                                                const gchar* nick,
                                                                                const gchar* blurb,
                                                                                GType object_type,
                                                                                GParamFlags flags);
void xbox_web_api_authentication_model_value_set_windows_live_response (GValue* value,
                                                                        gpointer v_object);
void xbox_web_api_authentication_model_value_take_windows_live_response (GValue* value,
                                                                         gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_windows_live_response (const GValue* value);
GType xbox_web_api_authentication_model_windows_live_response_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelWindowsLiveResponse* xbox_web_api_authentication_model_windows_live_response_new_fromQuery (GeeHashMap* query_params);
XboxWebApiAuthenticationModelWindowsLiveResponse* xbox_web_api_authentication_model_windows_live_response_construct_fromQuery (GType object_type,
                                                                                                                               GeeHashMap* query_params);
XboxWebApiAuthenticationModelWindowsLiveResponse* xbox_web_api_authentication_model_windows_live_response_new (void);
XboxWebApiAuthenticationModelWindowsLiveResponse* xbox_web_api_authentication_model_windows_live_response_construct (GType object_type);
GDateTime* xbox_web_api_authentication_model_windows_live_response_get_creation_time (XboxWebApiAuthenticationModelWindowsLiveResponse* self);
gpointer xbox_web_api_authentication_model_xasd_request_ref (gpointer instance);
void xbox_web_api_authentication_model_xasd_request_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xasd_request (const gchar* name,
                                                                       const gchar* nick,
                                                                       const gchar* blurb,
                                                                       GType object_type,
                                                                       GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xasd_request (GValue* value,
                                                               gpointer v_object);
void xbox_web_api_authentication_model_value_take_xasd_request (GValue* value,
                                                                gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xasd_request (const GValue* value);
GType xbox_web_api_authentication_model_xasd_request_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_access_token_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASDRequest* xbox_web_api_authentication_model_xasd_request_new (XboxWebApiAuthenticationAccessToken* access_token,
                                                                                              const gchar* relying_party,
                                                                                              const gchar* token_type,
                                                                                              const gchar* auth_method,
                                                                                              const gchar* site_name);
XboxWebApiAuthenticationModelXASDRequest* xbox_web_api_authentication_model_xasd_request_construct (GType object_type,
                                                                                                    XboxWebApiAuthenticationAccessToken* access_token,
                                                                                                    const gchar* relying_party,
                                                                                                    const gchar* token_type,
                                                                                                    const gchar* auth_method,
                                                                                                    const gchar* site_name);
const gchar* xbox_web_api_authentication_model_xasd_request_get_relying_party (XboxWebApiAuthenticationModelXASDRequest* self);
const gchar* xbox_web_api_authentication_model_xasd_request_get_token_type (XboxWebApiAuthenticationModelXASDRequest* self);
gpointer xbox_web_api_authentication_model_xasd_properties_ref (gpointer instance);
void xbox_web_api_authentication_model_xasd_properties_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xasd_properties (const gchar* name,
                                                                          const gchar* nick,
                                                                          const gchar* blurb,
                                                                          GType object_type,
                                                                          GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xasd_properties (GValue* value,
                                                                  gpointer v_object);
void xbox_web_api_authentication_model_value_take_xasd_properties (GValue* value,
                                                                   gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xasd_properties (const GValue* value);
GType xbox_web_api_authentication_model_xasd_properties_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASDProperties* xbox_web_api_authentication_model_xasd_request_get_properties (XboxWebApiAuthenticationModelXASDRequest* self);
XboxWebApiAuthenticationModelXASDProperties* xbox_web_api_authentication_model_xasd_properties_new (const gchar* auth_method,
                                                                                                    const gchar* site_name,
                                                                                                    const gchar* rps_ticket);
XboxWebApiAuthenticationModelXASDProperties* xbox_web_api_authentication_model_xasd_properties_construct (GType object_type,
                                                                                                          const gchar* auth_method,
                                                                                                          const gchar* site_name,
                                                                                                          const gchar* rps_ticket);
const gchar* xbox_web_api_authentication_model_xasd_properties_get_auth_method (XboxWebApiAuthenticationModelXASDProperties* self);
const gchar* xbox_web_api_authentication_model_xasd_properties_get_site_name (XboxWebApiAuthenticationModelXASDProperties* self);
const gchar* xbox_web_api_authentication_model_xasd_properties_get_rps_ticket (XboxWebApiAuthenticationModelXASDProperties* self);
gpointer xbox_web_api_authentication_model_xas_response_ref (gpointer instance);
void xbox_web_api_authentication_model_xas_response_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xas_response (const gchar* name,
                                                                       const gchar* nick,
                                                                       const gchar* blurb,
                                                                       GType object_type,
                                                                       GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xas_response (GValue* value,
                                                               gpointer v_object);
void xbox_web_api_authentication_model_value_take_xas_response (GValue* value,
                                                                gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xas_response (const GValue* value);
GType xbox_web_api_authentication_model_xas_response_get_type (void) G_GNUC_CONST;
gpointer xbox_web_api_authentication_model_xbox_user_information_ref (gpointer instance);
void xbox_web_api_authentication_model_xbox_user_information_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xbox_user_information (const gchar* name,
                                                                                const gchar* nick,
                                                                                const gchar* blurb,
                                                                                GType object_type,
                                                                                GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xbox_user_information (GValue* value,
                                                                        gpointer v_object);
void xbox_web_api_authentication_model_value_take_xbox_user_information (GValue* value,
                                                                         gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xbox_user_information (const GValue* value);
GType xbox_web_api_authentication_model_xbox_user_information_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASResponse* xbox_web_api_authentication_model_xas_response_new (void);
XboxWebApiAuthenticationModelXASResponse* xbox_web_api_authentication_model_xas_response_construct (GType object_type);
gpointer xbox_web_api_authentication_model_xast_request_ref (gpointer instance);
void xbox_web_api_authentication_model_xast_request_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xast_request (const gchar* name,
                                                                       const gchar* nick,
                                                                       const gchar* blurb,
                                                                       GType object_type,
                                                                       GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xast_request (GValue* value,
                                                               gpointer v_object);
void xbox_web_api_authentication_model_value_take_xast_request (GValue* value,
                                                                gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xast_request (const GValue* value);
GType xbox_web_api_authentication_model_xast_request_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_device_token_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASTRequest* xbox_web_api_authentication_model_xast_request_new (XboxWebApiAuthenticationAccessToken* access_token,
                                                                                              XboxWebApiAuthenticationDeviceToken* device_token,
                                                                                              const gchar* relying_party,
                                                                                              const gchar* token_type,
                                                                                              const gchar* auth_method,
                                                                                              const gchar* site_name);
XboxWebApiAuthenticationModelXASTRequest* xbox_web_api_authentication_model_xast_request_construct (GType object_type,
                                                                                                    XboxWebApiAuthenticationAccessToken* access_token,
                                                                                                    XboxWebApiAuthenticationDeviceToken* device_token,
                                                                                                    const gchar* relying_party,
                                                                                                    const gchar* token_type,
                                                                                                    const gchar* auth_method,
                                                                                                    const gchar* site_name);
const gchar* xbox_web_api_authentication_model_xast_request_get_relying_party (XboxWebApiAuthenticationModelXASTRequest* self);
const gchar* xbox_web_api_authentication_model_xast_request_get_token_type (XboxWebApiAuthenticationModelXASTRequest* self);
gpointer xbox_web_api_authentication_model_xast_properties_ref (gpointer instance);
void xbox_web_api_authentication_model_xast_properties_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xast_properties (const gchar* name,
                                                                          const gchar* nick,
                                                                          const gchar* blurb,
                                                                          GType object_type,
                                                                          GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xast_properties (GValue* value,
                                                                  gpointer v_object);
void xbox_web_api_authentication_model_value_take_xast_properties (GValue* value,
                                                                   gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xast_properties (const GValue* value);
GType xbox_web_api_authentication_model_xast_properties_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASTProperties* xbox_web_api_authentication_model_xast_request_get_properties (XboxWebApiAuthenticationModelXASTRequest* self);
XboxWebApiAuthenticationModelXASTProperties* xbox_web_api_authentication_model_xast_properties_new (const gchar* auth_method,
                                                                                                    const gchar* device_token,
                                                                                                    const gchar* site_name,
                                                                                                    const gchar* rps_ticket);
XboxWebApiAuthenticationModelXASTProperties* xbox_web_api_authentication_model_xast_properties_construct (GType object_type,
                                                                                                          const gchar* auth_method,
                                                                                                          const gchar* device_token,
                                                                                                          const gchar* site_name,
                                                                                                          const gchar* rps_ticket);
const gchar* xbox_web_api_authentication_model_xast_properties_get_auth_method (XboxWebApiAuthenticationModelXASTProperties* self);
const gchar* xbox_web_api_authentication_model_xast_properties_get_device_token (XboxWebApiAuthenticationModelXASTProperties* self);
const gchar* xbox_web_api_authentication_model_xast_properties_get_site_name (XboxWebApiAuthenticationModelXASTProperties* self);
const gchar* xbox_web_api_authentication_model_xast_properties_get_rps_ticket (XboxWebApiAuthenticationModelXASTProperties* self);
gpointer xbox_web_api_authentication_model_xasu_request_ref (gpointer instance);
void xbox_web_api_authentication_model_xasu_request_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xasu_request (const gchar* name,
                                                                       const gchar* nick,
                                                                       const gchar* blurb,
                                                                       GType object_type,
                                                                       GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xasu_request (GValue* value,
                                                               gpointer v_object);
void xbox_web_api_authentication_model_value_take_xasu_request (GValue* value,
                                                                gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xasu_request (const GValue* value);
GType xbox_web_api_authentication_model_xasu_request_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASURequest* xbox_web_api_authentication_model_xasu_request_new (XboxWebApiAuthenticationAccessToken* access_token,
                                                                                              const gchar* relying_party,
                                                                                              const gchar* token_type,
                                                                                              const gchar* auth_method,
                                                                                              const gchar* site_name);
XboxWebApiAuthenticationModelXASURequest* xbox_web_api_authentication_model_xasu_request_construct (GType object_type,
                                                                                                    XboxWebApiAuthenticationAccessToken* access_token,
                                                                                                    const gchar* relying_party,
                                                                                                    const gchar* token_type,
                                                                                                    const gchar* auth_method,
                                                                                                    const gchar* site_name);
const gchar* xbox_web_api_authentication_model_xasu_request_get_relying_party (XboxWebApiAuthenticationModelXASURequest* self);
const gchar* xbox_web_api_authentication_model_xasu_request_get_token_type (XboxWebApiAuthenticationModelXASURequest* self);
gpointer xbox_web_api_authentication_model_xasu_properties_ref (gpointer instance);
void xbox_web_api_authentication_model_xasu_properties_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xasu_properties (const gchar* name,
                                                                          const gchar* nick,
                                                                          const gchar* blurb,
                                                                          GType object_type,
                                                                          GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xasu_properties (GValue* value,
                                                                  gpointer v_object);
void xbox_web_api_authentication_model_value_take_xasu_properties (GValue* value,
                                                                   gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xasu_properties (const GValue* value);
GType xbox_web_api_authentication_model_xasu_properties_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXASUProperties* xbox_web_api_authentication_model_xasu_request_get_properties (XboxWebApiAuthenticationModelXASURequest* self);
XboxWebApiAuthenticationModelXASUProperties* xbox_web_api_authentication_model_xasu_properties_new (const gchar* auth_nethod,
                                                                                                    const gchar* site_name,
                                                                                                    const gchar* rps_ticket);
XboxWebApiAuthenticationModelXASUProperties* xbox_web_api_authentication_model_xasu_properties_construct (GType object_type,
                                                                                                          const gchar* auth_nethod,
                                                                                                          const gchar* site_name,
                                                                                                          const gchar* rps_ticket);
const gchar* xbox_web_api_authentication_model_xasu_properties_get_auth_nethod (XboxWebApiAuthenticationModelXASUProperties* self);
const gchar* xbox_web_api_authentication_model_xasu_properties_get_site_name (XboxWebApiAuthenticationModelXASUProperties* self);
const gchar* xbox_web_api_authentication_model_xasu_properties_get_rps_ticket (XboxWebApiAuthenticationModelXASUProperties* self);
gchar* xbox_web_api_authentication_model_xbox_user_information_to_string (XboxWebApiAuthenticationModelXboxUserInformation* self);
XboxWebApiAuthenticationModelXboxUserInformation* xbox_web_api_authentication_model_xbox_user_information_new (void);
XboxWebApiAuthenticationModelXboxUserInformation* xbox_web_api_authentication_model_xbox_user_information_construct (GType object_type);
gpointer xbox_web_api_authentication_model_xsts_request_ref (gpointer instance);
void xbox_web_api_authentication_model_xsts_request_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xsts_request (const gchar* name,
                                                                       const gchar* nick,
                                                                       const gchar* blurb,
                                                                       GType object_type,
                                                                       GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xsts_request (GValue* value,
                                                               gpointer v_object);
void xbox_web_api_authentication_model_value_take_xsts_request (GValue* value,
                                                                gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xsts_request (const GValue* value);
GType xbox_web_api_authentication_model_xsts_request_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_user_token_get_type (void) G_GNUC_CONST;
GType xbox_web_api_authentication_title_token_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXSTSRequest* xbox_web_api_authentication_model_xsts_request_new (XboxWebApiAuthenticationUserToken* user_token,
                                                                                              const gchar* relying_party,
                                                                                              const gchar* token_type,
                                                                                              const gchar* sandbox_id,
                                                                                              XboxWebApiAuthenticationDeviceToken* device_token,
                                                                                              XboxWebApiAuthenticationTitleToken* title_token);
XboxWebApiAuthenticationModelXSTSRequest* xbox_web_api_authentication_model_xsts_request_construct (GType object_type,
                                                                                                    XboxWebApiAuthenticationUserToken* user_token,
                                                                                                    const gchar* relying_party,
                                                                                                    const gchar* token_type,
                                                                                                    const gchar* sandbox_id,
                                                                                                    XboxWebApiAuthenticationDeviceToken* device_token,
                                                                                                    XboxWebApiAuthenticationTitleToken* title_token);
const gchar* xbox_web_api_authentication_model_xsts_request_get_relying_party (XboxWebApiAuthenticationModelXSTSRequest* self);
const gchar* xbox_web_api_authentication_model_xsts_request_get_token_type (XboxWebApiAuthenticationModelXSTSRequest* self);
gpointer xbox_web_api_authentication_model_xsts_properties_ref (gpointer instance);
void xbox_web_api_authentication_model_xsts_properties_unref (gpointer instance);
GParamSpec* xbox_web_api_authentication_model_param_spec_xsts_properties (const gchar* name,
                                                                          const gchar* nick,
                                                                          const gchar* blurb,
                                                                          GType object_type,
                                                                          GParamFlags flags);
void xbox_web_api_authentication_model_value_set_xsts_properties (GValue* value,
                                                                  gpointer v_object);
void xbox_web_api_authentication_model_value_take_xsts_properties (GValue* value,
                                                                   gpointer v_object);
gpointer xbox_web_api_authentication_model_value_get_xsts_properties (const GValue* value);
GType xbox_web_api_authentication_model_xsts_properties_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationModelXSTSProperties* xbox_web_api_authentication_model_xsts_request_get_properties (XboxWebApiAuthenticationModelXSTSRequest* self);
XboxWebApiAuthenticationModelXSTSProperties* xbox_web_api_authentication_model_xsts_properties_new (const gchar* user_token,
                                                                                                    const gchar* sandbox_id,
                                                                                                    const gchar* device_token,
                                                                                                    const gchar* title_token);
XboxWebApiAuthenticationModelXSTSProperties* xbox_web_api_authentication_model_xsts_properties_construct (GType object_type,
                                                                                                          const gchar* user_token,
                                                                                                          const gchar* sandbox_id,
                                                                                                          const gchar* device_token,
                                                                                                          const gchar* title_token);
gchar** xbox_web_api_authentication_model_xsts_properties_get_user_tokens (XboxWebApiAuthenticationModelXSTSProperties* self,
                                                                           int* result_length1);
void xbox_web_api_authentication_model_xsts_properties_set_user_tokens (XboxWebApiAuthenticationModelXSTSProperties* self,
                                                                        gchar** value,
                                                                        int value_length1);
const gchar* xbox_web_api_authentication_model_xsts_properties_get_sandbox_id (XboxWebApiAuthenticationModelXSTSProperties* self);
void xbox_web_api_authentication_model_xsts_properties_set_sandbox_id (XboxWebApiAuthenticationModelXSTSProperties* self,
                                                                       const gchar* value);
const gchar* xbox_web_api_authentication_model_xsts_properties_get_device_token (XboxWebApiAuthenticationModelXSTSProperties* self);
void xbox_web_api_authentication_model_xsts_properties_set_device_token (XboxWebApiAuthenticationModelXSTSProperties* self,
                                                                         const gchar* value);
const gchar* xbox_web_api_authentication_model_xsts_properties_get_title_token (XboxWebApiAuthenticationModelXSTSProperties* self);
void xbox_web_api_authentication_model_xsts_properties_set_title_token (XboxWebApiAuthenticationModelXSTSProperties* self,
                                                                        const gchar* value);
XboxWebApiAuthenticationAccessToken* xbox_web_api_authentication_access_token_new_from_windowsliveresponse (XboxWebApiAuthenticationModelWindowsLiveResponse* response);
XboxWebApiAuthenticationAccessToken* xbox_web_api_authentication_access_token_construct_from_windowsliveresponse (GType object_type,
                                                                                                                  XboxWebApiAuthenticationModelWindowsLiveResponse* response);
XboxWebApiAuthenticationAccessToken* xbox_web_api_authentication_access_token_new (void);
XboxWebApiAuthenticationAccessToken* xbox_web_api_authentication_access_token_construct (GType object_type);
XboxWebApiAuthenticationBaseAuthToken* xbox_web_api_authentication_base_auth_token_new_from_xasresponse (XboxWebApiAuthenticationModelXASResponse* token_response);
XboxWebApiAuthenticationBaseAuthToken* xbox_web_api_authentication_base_auth_token_construct_from_xasresponse (GType object_type,
                                                                                                               XboxWebApiAuthenticationModelXASResponse* token_response);
gboolean xbox_web_api_authentication_base_auth_token_is_valid (XboxWebApiAuthenticationBaseAuthToken* self);
gboolean xbox_web_api_authentication_base_auth_token_has_user_information (XboxWebApiAuthenticationBaseAuthToken* self);
gchar* xbox_web_api_authentication_base_auth_token_to_string (XboxWebApiAuthenticationBaseAuthToken* self);
XboxWebApiAuthenticationBaseAuthToken* xbox_web_api_authentication_base_auth_token_new (void);
XboxWebApiAuthenticationBaseAuthToken* xbox_web_api_authentication_base_auth_token_construct (GType object_type);
const gchar* xbox_web_api_authentication_base_auth_token_get_jwt (XboxWebApiAuthenticationBaseAuthToken* self);
void xbox_web_api_authentication_base_auth_token_set_jwt (XboxWebApiAuthenticationBaseAuthToken* self,
                                                          const gchar* value);
GDateTime* xbox_web_api_authentication_base_auth_token_get_issued (XboxWebApiAuthenticationBaseAuthToken* self);
void xbox_web_api_authentication_base_auth_token_set_issued (XboxWebApiAuthenticationBaseAuthToken* self,
                                                             GDateTime* value);
GDateTime* xbox_web_api_authentication_base_auth_token_get_expires (XboxWebApiAuthenticationBaseAuthToken* self);
void xbox_web_api_authentication_base_auth_token_set_expires (XboxWebApiAuthenticationBaseAuthToken* self,
                                                              GDateTime* value);
XboxWebApiAuthenticationModelXboxUserInformation* xbox_web_api_authentication_base_auth_token_get_user_information (XboxWebApiAuthenticationBaseAuthToken* self);
void xbox_web_api_authentication_base_auth_token_set_user_information (XboxWebApiAuthenticationBaseAuthToken* self,
                                                                       XboxWebApiAuthenticationModelXboxUserInformation* value);
XboxWebApiAuthenticationDeviceToken* xbox_web_api_authentication_device_token_new (void);
XboxWebApiAuthenticationDeviceToken* xbox_web_api_authentication_device_token_construct (GType object_type);
XboxWebApiAuthenticationRefreshToken* xbox_web_api_authentication_refresh_token_new_from_windowsliveresponse (XboxWebApiAuthenticationModelWindowsLiveResponse* response);
XboxWebApiAuthenticationRefreshToken* xbox_web_api_authentication_refresh_token_construct_from_windowsliveresponse (GType object_type,
                                                                                                                    XboxWebApiAuthenticationModelWindowsLiveResponse* response);
XboxWebApiAuthenticationRefreshToken* xbox_web_api_authentication_refresh_token_new (void);
XboxWebApiAuthenticationRefreshToken* xbox_web_api_authentication_refresh_token_construct (GType object_type);
XboxWebApiAuthenticationTitleToken* xbox_web_api_authentication_title_token_new (void);
XboxWebApiAuthenticationTitleToken* xbox_web_api_authentication_title_token_construct (GType object_type);
XboxWebApiAuthenticationUserToken* xbox_web_api_authentication_user_token_new (void);
XboxWebApiAuthenticationUserToken* xbox_web_api_authentication_user_token_construct (GType object_type);
GType xbox_web_api_authentication_xtoken_get_type (void) G_GNUC_CONST;
XboxWebApiAuthenticationXToken* xbox_web_api_authentication_xtoken_new (void);
XboxWebApiAuthenticationXToken* xbox_web_api_authentication_xtoken_construct (GType object_type);


G_END_DECLS

#endif
